### ISSUE TITLE
Remove aggregate id from domain abstractions

### ISSUE THREAD

**Issue by alexeyzimarev** [Eventuous/eventuous#111]
It seems like the need for the aggregate id inside domain objects is artificial. It both applies to having the aggregate id as part of the state, the `GetId` function and adding the aggregate id to events.

When handling a command on an existing aggregate, the aggregate id from the state object is not even used.

When handling a command for a new aggregate instance (initial command, initial state), the id is still coming from the command. What Eventuous forces people to do is to pass the id to the initial aggregate function, so it can add it to the initial event. In turn, the `When` function is expected to set the `Id` state property using the event data. The only reason for that is that the `OnNew` function doesn't have a way to get the id from the command. However, both `OnExisting` and `OnAny` have such function as a required parameter, so they don't really use the aggregate id stored in the state.

For the last point, there's no practical need to have the id inside the events, apart from projections. Right now, Eventuous projections use event properties to decide where to project things. However, the core event handler receives the `StreamEvent` instance, which also has the stream name. The stream name normally includes the aggregate id, and we already have a way to calculate the stream name from the aggregate id, so it should be possible to turn it in reverse and get the aggregate id from the stream name.

Right now, the only real impediment is the last point, as there's no _direct_ way to get the aggregate id from the stream name unless we use the default;t `AggregateType-AggregateId` function. Still, when an application uses a custom stream name calculation function, we can enforce the requirement for having a reverse function for projections. Alternatively, having such a function could be optional, and the projection handler will just get the stream name and would be able to calculate the aggregate id internally,

**Comment by bartelink** [comment]
Strongly agree with all of this.

As one approach for projections/reactions, in Equinox house style there's a [`module Reactions`](https://github.com/jet/dotnet-templates/search?q=module+Reactions) convention which hosts logic for parsing events and stream names (they are inverses of whatever you provide for composing them ([_examples_](https://github.com/jet/FsCodec/blob/master/src/FsCodec/StreamName.fs#L43-L108)) - i.e. every aggregate module has a `streamName` function that maps from value type ingredients of the stream name to the stream name etc).

🤔 Perhaps some light helpers that allow one to leverage pattern matching via `Deconstruct` might allow you to avoid having to provide N overloads to satisfy N naming schemes.
