### ISSUE TITLE
UnitTesting Aggregates fails because of versioning changes

### ISSUE THREAD

**Issue by ghandmann** [Eventuous/eventuous#124]
**Describe the bug**
I have a private project where i upgraded from Eventuous 0.8.X to 0.10.4. Everything went smooth and fine. But now all my unit tests fail. But to be honest, this even may be a wrong apporach on my side. ;)

The problem is, that after this massive [commit](https://github.com/Eventuous/eventuous/commit/f3774f9513773c1118216d10479927ba75472271) the `Apply` method of `Aggregate.cs` is not counting uncommited changes to the aggregate version anymore. This leads to the problem, that all aggrgate commands which utilize `EnsureExists` fail, if no events have been loaded.

Maybe calling a sequence of commands on the aggregate is the wrong approach to setup an aggregate state for testing? One could argue that i should create a list of domain events and feed them into the aggregate via `Load()`. But using these methods at least was quite convenient.

**To Reproduce**
I have created a small [reproducer](https://github.com/ghandmann/eventuous/blob/reproducer-aggregates-and-unit-tests/test/Reproducer/Program.cs)

**Expected behavior**
Unsure if the old or new behavior is to be expected.

**Comment by alexeyzimarev** [comment]
I guess it's a bug in `EnsureExists`. I will add your test.

**Comment by alexeyzimarev** [comment]
I already have a test for this, and it is failing. I really need to set up the automatic run in the CI...

**Comment by alexeyzimarev** [comment]
https://github.com/Eventuous/eventuous/releases/tag/0.10.5

**Comment by ghandmann** [comment]
That was :zap: fast! Thanks! Works fine now. :)
