### ISSUE TITLE
Error while reading stream: The input does not contain any JSON tokens

### ISSUE THREAD

**Issue by devployment** [Eventuous/eventuous#138]
**Describe the bug**

We are using Eventuous and EventStore Cloud. After updating Eventuous we get the following error

```
"Unable to read events from Qualification-11734: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. Path: $ | LineNumber: 0 | BytePositionInLine: 0."
```

Locally I'm running the code using Eventuous against a single ESDB instance running **21.10.5.0**. Our ESDB cluster version is **21.10.4.0**.

Interestingly I had the same issue locally, for some time, as I downgraded the ESDB version (from 22.x to 21.10.5.0) for debugging this. Then I switched Eventuous version to 0.10.x and up again. Locally I'm now run Eventuous 0.11.3 against ESDB 21.10.5.0.

Using Eventuous  0.11.3 against the ESDB cloud version (21.10.4.0) still shows the error above.

 Any idea or hint what can cause this?

**Comment by alexeyzimarev** [comment]
Maybe you can publish a repro? All the tests for ESDB pass for the latest version.

**Comment by devployment** [comment]
Seems like it is related to the event `Metadata`. For that particular stream, all events but the latest have `Metadata` associated. The latest event does not have `Metadata`at all. 

Currently trying to debug on that direction. Will come back with more info and/or repro if that is causing the issue.

**Comment by alexeyzimarev** [comment]
I can probably add a check for the metadata payload. You might be able also to see what the byte array contains when you read this event using the native client. It would be helpful to know what's the array size. If it's an empty array, it would be an easy fix. I also think that reading events could succeed with a warning if metadata deserialisation fails.

**Comment by devployment** [comment]
Here is a quickly bugled up test showing it failing.

https://github.com/devployment/Eventuous.MetadataTest

And yes, it is an empty array, read directly from the EventStoreClient

![image](https://user-images.githubusercontent.com/7137845/193279636-381938b7-5ba1-448d-a13c-27d00efb44c4.png)

**Comment by alexeyzimarev** [comment]
Should be fine in 0.11.4 when the nuget package is published (takes a few minutes)
