### ISSUE TITLE
Links to edit markdown in GitHub's documentation are broken due to language code in path

### ISSUE THREAD

**Issue by diegosasw** [Eventuous/eventuous#178]
The docs links to Edit this page, View this page, etc. are broken.

Example: at [eventuous.dev](https://eventuous.dev/docs/domain/domain-events/) the links point to
```
https://github.com/eventuous/docs/edit/master/content/en/docs/domain/domain-events.md
```
but the markdown is located at https://github.com/Eventuous/docs/blob/master/content/docs/domain/domain-events.md

The problem seems to be with the language at the path. If you remove `/en` it'll work.

**Comment by alexeyzimarev** [comment]
New version has the correct link
