### ISSUE TITLE
Eventuous least package dependencies

### ISSUE THREAD

**Issue by thijslimmen** [Eventuous/eventuous#18]
Hi Alex,

I'm trying to depend on Eventuous inside my netstandard2.1 project. It requires dotnet5.0. I think this project only consists of the core classes which should be compatible inside a netstandard2.0 project.

Could you configure it to be explicit about it being a netstandard2.0 project? Perhaps other projects are compatible with netstandard2.0 as well.

Kind regards,

Thijs

**Comment by thijslimmen** [comment]
Just read about net5.0. Upgraded all my netstandard projects to net5.0 :)

**Comment by alexeyzimarev** [comment]
The main issue was this bloody `ExternalInit`, which prevents records to be properly compiled. I ended up adding it everywhere, so I added the .NET Core 3.1 target in addition.

About .NET Standard, I am not sure as it's becoming obsolete and I don't really think we'll ever target .NET Framework.

I will add the .NET 6 target sometime in October.
