### ISSUE TITLE
Most of the AspNetCore extensions should likely be changed/moved to something more generic

### ISSUE THREAD

**Issue by cberthold** [Eventuous/eventuous#201]
**Is your feature request related to a problem? Please describe.**
I'm using Eventuous to tinker with ideas using Azure Functions.  Everything but the automatic mapping is required to build a solution with any technology.

**Describe the solution you'd like**
Move extension methods such as AddAggregateStore to the core of Eventuous or something more clear related to Command / Application services.  It wasn't clear I needed AspNetCore when I'm not directly building anything with it.  (Yes I know AspNetCore exists deep into Azure Functions Host + Functions CLI at runtime)

**Describe alternatives you've considered**

**Additional context**

**Comment by alexeyzimarev** [comment]
These extensions are the `AspNetCore` project as it depends on `Microsoft.Extensions.Hosting`. The whole DI story with DepencencyInjection extensions comes from ASP.NET Core, and it's [documented](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-7.0) like that too. I know that Microsoft calls it ".NET Platform Extensions" now, but I don't really want to keep changing things as they decide to move stuff around.

Would you agree that making it clearer in the documentation is enough?
