### ISSUE TITLE
Exciting and Refreshing

### ISSUE THREAD

**Issue by dthk-cogmatix** [Eventuous/eventuous#24]
I just wanted to say I'm excited to see where this project goes and it's refreshing to see a new approach on event sourcing.  I have an upcoming project with a valid use-case / requirement for an Event Sourcing database and I'm looking for frameworks to help bootstrap that initiative.

There are very few frameworks for .NET that support event sourcing, and the few that do, all have the problem(s) you've outlined with their event bus approach to handling the write side and the query/read handlers.  I think you're the only project I've come across that is building with Event Source database first (instead of a relational or document database overlay) that lets you approach the problem differently.

I'm going to give you guys a try, hopefully I"ll be able to contribute back, and at the very least If I'm a bit premature in adoption, I'm excited to follow your progress.

**Comment by alexeyzimarev** [comment]
Thanks! And many thanks for sponsoring the project :)
