### ISSUE TITLE
Follow RFC 7807: Problem Details for HTTP APIs

### ISSUE THREAD

**Issue by Frikki** [Eventuous/eventuous#242]
**Is your feature request related to a problem? Please describe.**
When all HTTP APIs define their own “error” JSON objects, it becomes a nightmare for developers to remember or find which members are available. And it’s hard for machines to read them.

**Describe the solution you'd like**
_[RFC 7807: Problem Details for HTTP APIs](https://datatracker.ietf.org/doc/html/rfc7807)_ already reached consensus in the IETF community on how to define a “problem detail” as a way to carry machine-readable details of errors in an HTTP response to avoid the need to define new error response formats for HTTP APIs, not to replace existing domain-specific formats.

It would be super if Eventuous would follow the standard and be a role model like it is for Event Sourcing. [Section 3](https://datatracker.ietf.org/doc/html/rfc7807#section-3) details the members of a Problem Detail Object.

**Describe alternatives you've considered**

- Stay with the format already defined if it’s a more appropriate way of carrying the error.
- Adopt a significant player’s (e.g., Google Cloud) custom error object.

**Additional context**

Here is an example of what the current **`400 Bad Request`** response looks like:

```json
HTTP/1.1 400 Bad Request
   Content-Type: application/json
   Content-Language: en

{
  "errorMessage": "Unable to append events to Booking-123: Type RoomBooked is not registered in the type map",
  "message": "Error handling command BookRoom",
  "state": null,
  "success": false,
  "changes": null
}
```

Here is an example of what a **`400 Bad Request`** response with problem details would look like:

```json
HTTP/1.1 400 Bad Request
   Content-Type: application/problem+json
   Content-Language: en

{
    "type": "https://eventuous.dev/errors/unable-to-handle-command",
    "title": "Unable to handle command",
    "status": 400,
    "detail": "Unable to append events to Booking-123: Type RoomBooked is not registered in the type map. See https://eventuous.dev/docs/persistence/serialisation/#type-map",
    "instance": "/bookings/book",
    "success": false,
    "state": null,
    "changes": null
}
```

**Comment by makp0** [comment]
@Frikki, could you please include **before** for ease of comparison?

**Comment by Frikki** [comment]
Sure thing, @makp0. Updated OP.

**Comment by Frikki** [comment]
While inspecting the Eventuous source code, I noticed that `Eventuous.AspNetCore.Web`’s `ResultExtension` uses [`ProblemDetails`](https://github.com/Eventuous/eventuous/blob/330506feb5b875b7c7b8bc73dfef8f80d1447790/src/Extensions/src/Eventuous.AspNetCore.Web/ResultExtensions.cs#L16) from `Microsoft.AspNetCore.Web`.

[An article at CodeMaze](https://code-maze.com/using-the-problemdetails-class-in-asp-net-core-web-api/) also addresses the issue and the standard implemented in ASP.NET Core Web API.

**Comment by alexeyzimarev** [comment]
Does the latest preview version cover these needs?
