### ISSUE TITLE
Consider adding the possibility to save and access metadata 

### ISSUE THREAD

**Issue by ricksecretin** [Eventuous/eventuous#26]
It would be nice to be able to save and access metadata easily in eventuous.

1. Currently a 'null' is saved for metadata when appending events to the eventstore.
It would be nice if there was a method that you could override like 'AddMetadata' when inheriting from AggregateStore to set the metadata. 

2. Currently no access to metadata in event handlers

This would be nice to use the build-in $correlationId of eventStore.
Currently I had to reimplement some of the already implemented classes like aggregateStore to make this possible.

Thanks.

**Comment by alexeyzimarev** [comment]
Yes, I am working on that already. The upcoming release has a requirement to allow storing and retrieving metadata also because of the distributed tracing feature, which is coming.

**Comment by alexeyzimarev** [comment]
Btw @ricksecretin if you have any thoughts about #9 please write there.

**Comment by alexeyzimarev** [comment]
@ricksecretin any thoughts about what to do with the loaded metadata when reading events? The aggregate store can't really do anything with it.

**Comment by ricksecretin** [comment]
@alexeyzimarev for me personally I don't think it's useful to have access to it when calling the aggregateStore.
I don't directly see a use case where you would need the metadata.

**Comment by alexeyzimarev** [comment]
Right, that's my thought as well. So far, both `ReceivedEvent` and `ProducedMessage` got metadata.

This commit https://github.com/Eventuous/eventuous/pull/52/commits/f0afa0ab628e550c90645d7b6208d7c26c9d4f9e adds traces to the meta for producers. As it uses the `AcitivySource` API, it works out of the box with OpenTelemetry, although I plan to add some extensions to make it easier. Also, the parent-child relationships will work when upstream and downstream parts are instrumented. You'd need to avoid using tags that start with `eventuous` as those are reserved. And I forgot to add `$correlationId` default EventStore meta but I will add it later.
