### ISSUE TITLE
Subscriptions v2

### ISSUE THREAD

**Issue by alexeyzimarev** [Eventuous/eventuous#28]
## Current status

- Subscriptions currently implement hosted services as they run in the background
- Subscriptions are responsible for retrieving the initial checkpoint
- Subscriptions also store checkpoints after processing an event, one by one

## Issues

- Not easy to use subscriptions outside of ASP.NET Core scope, forced Hosting and DI dependency
- Overuse of a dummy checkpoint store for subscriptions that don't have the checkpoint maintenance (RMQ, PubSub)
- Batched checkpointing has to be implemented by the checkpoint store
- Impossible to partition event handlers as the sequential processing will break

## Plan

- Separate subscriptions from hosting
- Make subscriptions independent of ASP.NET Core
- Remove the checkpoint concern from the core subscription entirely
- Introduce `SubscriptionContext`
- Allow explicit ACK and NACK using the context, per event handler
- Handle ACK and NACK only when all handlers respond (should there be a timeout too?)
- Handle ACK and NACK in a way that is native to the transport
- For subscriptions with a client-side checkpoint, only commit the checkpoint for the earliest ACKed event position

Thoughts, feedback - please reply here.

**Comment by dthk-cogmatix** [comment]
Question:  What is the intent of SubscriptionContext?

My question comes from the following:
My subscribers are tied to a specific underlying technology.  MongoDB subscriber, Redis Subscriber, etc.  When an event is handled, I may have several handlers/updates to make in the database.  If one of my handlers fail, I don't want to have a partial update of my read models.  Ideally, I would like to have some sort of "Context" injected into the handlers handling that event which could include a database session or transaction.  Each processed event would effectively have its own lifetime scope (similar to each asp.net web request).

**Comment by alexeyzimarev** [comment]
The reason to have the context is to have a container of elements where we can include more than just the actual payload (event). Examples are metadata (headers), cancellation token, any kind of system information from the transport, etc.

I want the context also to have the possibility to ACK events rather than rely on an event handler to either complete or throw.

Concerning your question @dthk-cogmatix that should be possible to do by building a consume pipe. You should be able to have a middleware, which opens a session, adds the session to the context, and passes the context to the actual handler. Normally handlers are stateless, so the context is the place where the state is shared within the consume pipeline.

**Comment by alexeyzimarev** [comment]
Here is the issue detailed:

# Eventuous Subscriptions RFC

## Too much abstraction

Subscriptions need to become even more connected to their underlying transports. Right now the subscription core has a dependency on a checkpoint store, although only StreamSubscription and AllStreamSubscriptions are using it. Neither persistent ESDB subscriptions nor broker-based ones like PubSub or RabbitMQ use the checkpoint store, so we have to give the NoOp store just so we have one. It’s waste and should be removed.

## Context

Subscriptions are lacking context. There are good examples of consuming messages in a context including:

- `HttpMessageHandler` from `HttpClient`
- `ConsumeContext` of MassTransit
- `HttpContext` in WebAPI

Adding a context would allow to finally add headers or metadata to the whole pipe. We can also finally add middlewares, so things like retries would be possible to address from the outside of event handlers.

## Delayed ACK

Both those issues have something in common. If a subscription doesn’t care about checkpointing, this power needs to be given to the consumer. There are two scenarios:
- Checkpoint-less brokers could support message ACK and NACK natively. The context would provide such a function, like `ctx.Ack()`.
- When there’s a need for a checkpoint, the solution is unclear. Delayed ACK creates issues if events are, for example, partitioned for processing. That’s why Kafka has only one consumer per partition max, as it’s much easier to keep checkpoints (offsets in Kafka terms) per partition managed by a single consumer, which processes messages in strict order.

**Therefore**: it is clear what to do until we allow partitioned processing of events in a single subscription, which must process events in order within one partition. Maintaining a single checkpoint, in this case, is not easy. However, supporting this scenario is a big opportunity as it allows to speed up read-model projections a lot. Right now, this can only be done by using an additional event log-based broker like Kafka as an external durable partitioner.

The issue can be illustrated by this diagram:
![image](https://user-images.githubusercontent.com/2821205/129751369-d1979d10-98c5-4da0-9cc4-18feb43923df.png)

It would be simpler if we’d have a guaranteed sequence of events where the current offset increases by one. However, ESDB `$all` stream poses a challenge of having a commit position, which is in bytes, so it’s not incremented by one.

My current idea is:
- Add a sequence, starting from zero. Each event pushed to the consumer pipeline gets both the sequence number and the commit position (when subscribing to $all)
- Maybe the sequencer needs to live outside of the subscription itself, as a separate class instance
- The sequencer knows what events were pushed to the consumer pipeline
- ACKs come back to the sequencer, potentially out of order
- All unacknowledged sequence elements remain in the “in-flight” list, which is ordered by sequence number
- After each ACK, the sequencer marks the sequence element as acknowledged
- Then, the sequence is checked for the first unacknowledged element in the sequence
- The element just before the first unacknowledged element will contain the offset of the latest acknowledged element (event), which can be then committed to the checkpoint store 

It’s a bit cumbersome, so I am still considering alternatives.

**Comment by alexeyzimarev** [comment]
| | ES Catch-up | ES Persistent | Kafka | PubSub | RMQ |
| -- | ------------- | ------------- | ------ | ------- | ---- |
| Consumer groups | - | X | X | - | - |
| Order | X | - | X | Key | - |
| Checkpoint | X | - | Optional | - | - |

**Comment by alexeyzimarev** [comment]
#52 introduced explicit consumers and consume contexts. Consumers can be composed. Some subscriptions use consumers composition already. Delayed acknowledgement context is there, and it's used by RMQ and ESDB catch-up subscriptions.

**Comment by alexeyzimarev** [comment]
Closed by #52 with #54 still open
