### ISSUE TITLE
Does it make sense to keep `Aggregate` without state?

### ISSUE THREAD

**Issue by alexeyzimarev** [Eventuous/eventuous#318]
I have never inherited aggregates from plain `Aggregate` and always use `Aggregate<TState>`.

The question is if Eventuous should keep `Aggregate` or bundle everything to `Aggregate<TState>`? It will substantially simplify the code for command services, both aggregate-based, and functional.

**Comment by mytresor** [comment]
We have been using Eventuous for almost a year, have many dozens of Aggregates, and also have never needed a plain Aggregate without a state.

**Comment by solomkae** [comment]
yep, exactly same picture as @mytresor said

**Comment by diegosasw** [comment]
I've used always aggregate with state, but this is an interesting subject.

I'd like to explore the possibility of appending events to a stream without reading the stream of events to hydrate the aggregate.

For example, If I have a StaffAvailability aggregate or concept and some actions don't require any business logic, such as SetAvailable, and SetUnavailable regardless of current state, is there any way with Eventuous to append to stream the event without applying previous ones? I suppose this is different to the concept of aggregate without state.

**Comment by alexeyzimarev** [comment]
@diegosasw Well, would you append `SetAvailable` if it has already been set to `Available` before? You might want to read one last even only for that. Supporting that is something I thought of, like read stream strategy similar to Equinox.

**Comment by diegosasw** [comment]
@alexeyzimarev yes, you're right, Ideally I'd like to read the last event for that, therefore I can't imagine an Aggregate without state either.

If Eventuous supports reading events backwards it could be very useful for this and also for snapshots (unless every event always has the current state so that state can be hydrated by only reading the last event). That'd be really interesting actually.

**Comment by alexeyzimarev** [comment]
Btw, any ideas of demanding to read from the back? I thought it could be an optional argument for app services (read strategy). I was discussing it with Ruben, I think something similar exists in Equinox.

**Comment by diegosasw** [comment]
A read strategy argument sounds good. Would that also be related to snapshots?
My two cents: a read strategy optional argument in the app service with a delegate checkpoint, event type or counter of events to act as the stopping point, so that the aggregate is instantiated from that point onwards.

**Comment by alexeyzimarev** [comment]
> A read strategy argument sounds good. Would that also be related to snapshots?

Yes! Fine-grained reads are definitely required for snapshots, where the strategy would be "read until <type>".

**Comment by alexeyzimarev** [comment]
Here https://github.com/Eventuous/eventuous/pull/350 I got `Aggregate` removed and `Aggregate<TState>` is the only one. It became possible to simplify command services. However, the drawback is the API change with one more generic constraint. Also, all command services now only require `TState` (essentially), so it looks like commands are related to state. The API is simpler but it hurts my eyes a bit.
Thoughts?
