### ISSUE TITLE
Memory leak (CancellationTokenSource) in AsyncHandlingFilter

### ISSUE THREAD

**Issue by Steve-OH** [Eventuous/eventuous#328]
**Describe the bug**
There is a memory leak in AsyncHandlingFilter. A new linked `CancellationTokenSource` is created in line 38:

```
var cts = CancellationTokenSource.CreateLinkedTokenSource(ctx.CancellationToken, ct);
```
but is never disposed. This should be:

```
using var cts = CancellationTokenSource.CreateLinkedTokenSource(ctx.CancellationToken, ct);
```

**To Reproduce**

Any code that uses an event filter in a subscription will exhibit the memory leak. This can be seen using a memory profiler like dotMemory; just process a few million do-nothing events and watch live allocated memory grow steadily.

I can create a test case (that can be run in dotMemory to see the problem--I don't think there's a practical unit test for this), but since the existing code is pretty obviously wrong, I'm not sure it's worth the effort.

**Expected behavior**

Memory should not leak.

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2
 - Browser: N/A
 - Version: N/A

**Comment by bartelink** [comment]
Been there: https://github.com/jet/propulsion/pull/221
cleaned up helper https://github.com/jet/propulsion/commit/1b4221b6177201f3e9c603af38a1ec278bb1e5be
