### ISSUE TITLE
Aggregate state not being saved after executing an async method 

### ISSUE THREAD

**Issue by claudiuchis** [Eventuous/eventuous#33]
This is likely not an issue with the Eventuous framework, but I can't figure out why an aggregate's state doesn't get saved after executing an async method on the aggregate. I made sure that async/await is used where needed.
Here is a link to a sample project (it has only the bare minimum to reproduce this issue): 

https://github.com/claudiuchis/Eventuous.Sample

There are 2 events:
- WidgetCreated - created by calling the post endpoint on the WidgetController
- WidgetReacted - created as a reaction to the WidgetCreated event after calling an "external" service.

The 2nd event (WidgetReacted) is not appended (e.g. saved) to the stream, so it looks like the reaction doesn't get a chance to complete, and thus the event doesn't get saved. No clue why, as the service does await on the command issued by the reactor.

Any help is much appreciated.

**Comment by claudiuchis** [comment]
A real world scenario is sending an email after a user signs up.

**Comment by claudiuchis** [comment]
As I thought, there is no issue with the framework. The issue was with my code, I was using the non-async version of the OnExisting when adding the async handler. I switched to OnExistingAsync and the problem went away.

**Comment by alexeyzimarev** [comment]
Yeah, there are some docs lacking in that regard. I plan to have a better API coverage in the docs when the new version gets out.
