### ISSUE TITLE
DefaultEventSerializer - throw error when Type not found

### ISSUE THREAD

**Issue by StevenBlair123** [Eventuous/eventuous#4]
Having a play around with this framework and struggled to get the Subscription service working.
I pulled down your repository so I could debug it, and it turned out I hadn't registered my Type.
Opted for the DefaultEventSerializer, which silently handles unknown events.

Wonder if an option to throw an error on this would be useful?
Might be better that happen, than skip passed an event because someone forgot to register the Event.

**Comment by alexeyzimarev** [comment]
Have you checked the [serialization docs](https://eventuous.dev/docs/persistence/serialisation/)?

Types must be registered in the `TypeMap` as we don't want to depend on CLR type names when deserialising previously persisted events. I usually do it in `Startup`, but mappings themselves live in one place per domain model functional component.

For example, in the test project, all the mappings are registered in the static constructor of the events holder itself:

https://github.com/Eventuous/eventuous/blob/70717a805cc7baeccd52e2f37ae3da9169f220a2/test/Eventuous.Tests/Model/BookingEvents.cs#L15-L20

**Comment by StevenBlair123** [comment]
Alexey,

I had looked over that when I was working out what I had missed out.
It was more a suggestion to help diagnose a missing TypeMap entry

So something like:

`DefaultEventSerializer defaultEventSerializer = new(true); //throw an exception if we don't find a Type`

And with your example:

```
public static void MapBookingEvents() { 
     TypeMap.AddType<RoomBooked>("RoomBooked"); 
     TypeMap.AddType<BookingPaymentRegistered>("BookingPaymentRegistered"); 
     //TypeMap.AddType<BookingCancelled>("BookingCancelled"); //user forgets to add this.
     TypeMap.AddType<BookingImported>("BookingImported"); 
 }
```

**Comment by alexeyzimarev** [comment]
But how can it know what types are needed? It's just a serializer. Until you hit an event, which hasn't been mapped, it's impossible to know.

I believe it's something that's easily caught in tests.

**Comment by alexeyzimarev** [comment]
A long time ago I was using a fallback to the CLR type name. However, it did more damage than good. When the serializer throws, you see it very fast. If it keeps storing events, which weren't mapped, you will be caught by surprise when you look at the store and see the wrong event type there, which is impossible to fix without migrating the streams.

**Comment by alexeyzimarev** [comment]
I just got an idea. What if we can create a static analyser, which will trigger warnings in the editor/IDE if you use event types in `When` for the aggregate state, subscriptions, etc, but they aren't mapped anywhere. I am not sure if it's even possible, but maybe it's something to consider.

**Comment by StevenBlair123** [comment]
Alexey,

Yes, I think that would be great if it was possible. Knowing about this at compile time would be great.
So somehow get the IDE to check your aggregate / projection and make sure we have a corresponding entry in TyepMap.

**Comment by alexeyzimarev** [comment]
@StevenBlair123 have to park the code analysis idea facing some substantial work around subscriptions and diagnostics.

However, I got some ideas from other projects. For example, would an event type name attribute be a better solution? At least it will be obviously visible in the code.

**Comment by alexeyzimarev** [comment]
Check the PR 👆

**Comment by alexeyzimarev** [comment]
More checks added by #48
