### ISSUE TITLE
Kafka producer

### ISSUE THREAD

**Issue by alexeyzimarev** [Eventuous/eventuous#43]
Add Kafka producer, which should be easy

**Comment by RagingKore** [comment]
Not quite but shall I give it a go? ;)

**Comment by alexeyzimarev** [comment]
I meant I made this a while ago. I know it's awaiting so it's not as fast as it could be.
https://github.com/EventStore/replicator/blob/master/src/EventStore.Replicator.Kafka/KafkaWriter.cs

**Comment by alexeyzimarev** [comment]
The basic one is  #90. The one with schema registry needs to wait until the subscription is done.
