### ISSUE TITLE
Initializing Aggreagate from Pre-existing state

### ISSUE THREAD

**Issue by jeremiahredekop** [Eventuous/eventuous#66]
Hi Alexey,

Nice library 👍 

Is there any mechanism in this framework to create an aggregate from a pre-existing state object and version (ie - snapshots)? 

Even If not, would you be open to any pull requests to allow the possibility as a basic implementation?

**Comment by alexeyzimarev** [comment]
Not yet, but I am considering the full-pledged snapshotting built-in.

My worry is that technical snapshotting provokes a quick fix for long streams, which in many cases is a model design flaw. Not always, I must admit.

**Comment by alexeyzimarev** [comment]
Want to combine it with #64
