### ISSUE TITLE
Subscription durability

### ISSUE THREAD

**Issue by alexeyzimarev** [Eventuous/eventuous#7]
We handle subscriptions drops, but it would be nice to have a story around failures in event handlers.

When handling an event in a subscription fails, the following possible scenarios apply:

| Reason | Remedy |
|---------|---------|
| Transient failure  | Retry individual handlers |
| Permanent failure (poison) | Log and continue <br> Full stop, make unhealthy |
| Checkpoint storage failure | Endless retry, make unhealthy | Ignore, move on and keep trying | 

We could support all the scenarios. The question is only how to configure it, and what is the good default.

**Comment by alexeyzimarev** [comment]
For some subscription types, we have even more options.

RMQ subscription can:
- Ack
- Nack and drop
- Nack and requeue

ESDB persistent subscriptions can:
- Ack
- Nack
- Park

How the subscription could know what to do with the message?

**Comment by alexeyzimarev** [comment]
Google PubSub - Ack and Nack.

**Comment by martinothamar** [comment]
Maybe [Polly](https://github.com/App-vNext/Polly) can be used here? The API is pretty flexible and seems to be the .NET goto for advanced error handling, reties etc. Not too familiar with this library yet (on my todo list), but a builder pattern of some sort might be good here?

```csharp
services.AddEventHandler<SomeHandler>()
    .WithPolicy(...);
```

MS docs on HttpClient integration with Polly: https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/implement-http-call-retries-exponential-backoff-polly

**Comment by martinothamar** [comment]
> Log and continue. Full stop, make unhealthy

This would indicate that the policy in this case should be able to return a signal/enum value or something to indicate what the service should do about the handler? Not sure how "plug and play" Polly would be for that scenario

**Comment by alexeyzimarev** [comment]
@martinothamar Polly can help with retries and circuit breakers. However, as I mentioned, some transports have their own retry capability. And RMQ in particular has a way to re-queue the message, which is very helpful when handling "it's not there yet" situations (quite common).

If we should have middlewares in subscriptions, I haven't decided yet. #28 brings some foundation to the future improvements of subscriptions.

One principle of Eventuous is **not** to ignore the transport, provide as little as possible abstraction on top of it, and use the transport native capabilities.

Adding policies to handlers is something I also thought of, looking at `HttpClient` Polly extensions. The issue there is the scope, as if you look at the code of those extensions, you'll see that it's not really a good fit for event handlers.

**Comment by alexeyzimarev** [comment]
@martinothamar btw I just realised that I completely agree with what you wrote. I also hardly see a plug-and-play scenario for Polly here.

The current consumer implementation allows, in theory, to implement a retrying consumer. However, as you rightfully mentioned, how does the consumer know to which handler the policy applies and what to do if only one of the handlers fails?

I can now think of the following:
- Extend `AddEventHandler` with some sort of subscription handler builder
- Such a builder can allow wrapping the handler in a retry handler
- Add a E-s.Subscriptions.Polly package, which would contain a Polly-driven retry handler
