### ISSUE TITLE
Headers vs metadata

### ISSUE THREAD

**Issue by alexeyzimarev** [Eventuous/eventuous#9]
EventStoreDB allows adding metadata to events in any format, as it's just a byte array. Also, an event has a content type, which spans both payload and metadata.

However, subscriptions and producers can support event streaming using brokers. Most of the brokers don't support metadata as such and have message headers instead. Headers are key-value maps, not complex objects. RabbitMQ represents them as text, similar to HTTP headers. Google PubSub uses attributes, which are also key-value pairs, represented as a string-string dictionary.

My thought is to limit metadata to such a dictionary format. It would help to handle serialisation concerns and allows adding default headers like trace and span id, correlation id and so on.

**Comment by JulianMay** [comment]
I have yet had the need for anything but string/string key/values in metadata

**Comment by alexeyzimarev** [comment]
I lean towards that too @JulianMay (and 👋). I see that lots of transports just expect headers or attributes. So, I will use a simple map. Those who need something more complex can always put a serialised payload there.

**Comment by alexeyzimarev** [comment]
Landed on meta, which are headers. Complex objects won't work for infra bits that only support headers.
