### ISSUE TITLE
When we have any exception at projection level... It does not get recorded in logs

### ISSUE THREAD

**Issue by shashikantpawar21** [Eventuous/eventuous#94]
When we have any exception at projection level... It does not record in seq or any logs ..

We would never know why the mongodb fails and only option is to restart the containers..

Is there anything for this ?

**Comment by alexeyzimarev** [comment]
You can try adding internal logs: https://github.com/Eventuous/dotnet-sample/blob/7502eccb48c90744a7f2e86151a040aa0c24e199/Bookings/Program.cs#L38

**Comment by alexeyzimarev** [comment]
Subscriptions were switched to the normal logger, so any issue should be logged normally within the scope of the subscription logger.
