### ISSUE TITLE
Document & Projected document namespace

### ISSUE THREAD

**Issue by Zonorai** [Eventuous/eventuous#95]
Hi I have a project where I'm using mediatR commands and sharing them with my blazor client, so instead of having Handlers + Requests in one assembly I split them and reimplement the handlers on the client side for the same requests.
My concern right now is that the client(Requests only) library has to reference the mongo driver and subscriptions because of the ProjectedDocument record, any chance that these two records can move down to the core level?
example the ClaimDocument is a projected document
`using MediatR;
namespace Tenants.ApplicationInterface.Claims.Queries.ListClaims;

public class ListClaimsQuery : IRequest<List<ClaimDocument>>
{
}`

**Comment by alexeyzimarev** [comment]
If I may ask why do you need MrdiatR for handling queries? Queries must return the result synchronously, I consider using any sort of middleware for queries as an anti-pattern, but it might be just my thing.

**Comment by Zonorai** [comment]
Thanks for answering and thanks for the library, I've found it very helpful thus far and avoided some pitfalls I was unaware of by watching your videos, also learned a lot from you in general. I've never considered that but I am using it as a means to authorize everything instead of authorizing on the presentation side (Controller) motivation being that the authorization becomes independent of the type of application as long a I'm in the .net framework and have access to the IAuthorizationService, what would you suggest I do instead?

Abstracting my queries into something like IClaimQueries and then creating a dependency on IAuthorizationService will solve my authorization issue, the need for authorization being independent from the API stems from the fact that my app might have to be sometimes online. Is that more in line with your thoughts?

**Comment by alexeyzimarev** [comment]
Normally you do authentication and basic authorisation using auth policies and `IAuthorizationService` is done by ASP.NET itself in a middleware, so you get the request pre-authorised. Of course, you could need things like "what can the user see" in the query, but you don't need MediatR for it.

I normally avoid decoupling queries from the read model database engine, as they are naturally coupled, that's the whole point of CQRS. Then, you can have the query service as a dependency in the controller. I usually split query controllers from command controllers also for that reason, as they serve different purposes and need different dependencies.

**Comment by alexeyzimarev** [comment]
I will close this one, if you have any more comments please still write here.
